_BASE_: ../Cityscapes-PanopticSegmentation/Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: "detectron2://DeepLab/R-52.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  SEM_SEG_HEAD:
    NUM_CLASSES: 133
    LOSS_TOP_K: 1.0
    USE_DEPTHWISE_SEPARABLE_CONV: True
  PANOPTIC_DEEPLAB:
    STUFF_AREA: 4096
    NMS_KERNEL: 41
    SIZE_DIVISIBILITY: 640
    USE_DEPTHWISE_SEPARABLE_CONV: True
  PREV_OFFSET_HEAD:
    NAME: "PanopticDeepLabPrevOffsetHead"
    IN_FEATURES: ["res2", "res3", "res5"]
    PROJECT_FEATURES: ["res2", "res3"]
    PROJECT_CHANNELS: [32, 64]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    HEAD_CHANNELS: 32
    CONVS_DIM: 128
    COMMON_STRIDE: 4
    NORM: "SyncBN"
    PREV_OFFSET_LOSS_WEIGHT: 0.01
DATASETS:
  TRAIN: ("kitti_mots_train",)
  TEST: ("kitti_mots_val",)
SOLVER:
  BASE_LR: 0.0005
  MAX_ITER: 200000
  IMS_PER_BATCH: 64
INPUT:
  FORMAT: "RGB"
  GAUSSIAN_SIGMA: 8
  CROP:
    ENABLED: False
    TYPE: "absolute"
    SIZE: (640, 640)
