MODEL:
  META_ARCHITECTURE: "Post"
  WEIGHTS: "./models/model_0004999.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
    FREEZE_AT: 0
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res5"]
    RES5_DILATION: 2
    DEPTH: 50
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  SEM_SEG_HEAD:
    NAME: "PanopticDeepLabSemSegHead"
    IN_FEATURES: ["res2", "res3", "res5"]
    PROJECT_FEATURES: ["res2", "res3"]
    PROJECT_CHANNELS: [32, 64]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    HEAD_CHANNELS: 256
    CONVS_DIM: 256
    COMMON_STRIDE: 4
    NUM_CLASSES: 133
    LOSS_TYPE: "hard_pixel_mining"
    NORM: "SyncBN"
    LOSS_TOP_K: 1.0
    USE_DEPTHWISE_SEPARABLE_CONV: True
  INS_EMBED_HEAD:
    NAME: "PanopticDeepLabInsEmbedHead"
    IN_FEATURES: ["res2", "res3", "res5"]
    PROJECT_FEATURES: ["res2", "res3"]
    PROJECT_CHANNELS: [32, 64]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    HEAD_CHANNELS: 32
    CONVS_DIM: 128
    COMMON_STRIDE: 4
    NORM: "SyncBN"
    CENTER_LOSS_WEIGHT: 200.0
    OFFSET_LOSS_WEIGHT: 0.01
  PREV_OFFSET_HEAD:
    NAME: "PrevOffsetHead"
    IN_FEATURES: ["res2", "res3", "res5"]
    PROJECT_FEATURES: ["res2", "res3"]
    PROJECT_CHANNELS: [32, 64]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    HEAD_CHANNELS: 32
    CONVS_DIM: 128
    COMMON_STRIDE: 4
    NORM: "SyncBN"
    PREV_OFFSET_LOSS_WEIGHT: 0.01
  PANOPTIC_DEEPLAB:
    STUFF_AREA: 4096
    CENTER_THRESHOLD: 0.1
    NMS_KERNEL: 41
    TOP_K_INSTANCE: 20
    SIZE_DIVISIBILITY: 64
    USE_DEPTHWISE_SEPARABLE_CONV: True
DATASETS:
  TRAIN: ("rob_mots_train",)
  TEST: ("rob_mots_val",)
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.0005
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MAX_ITER: 2000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 6
INPUT:
  MIN_SIZE_TRAIN: (384,)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 384
  MAX_SIZE_TRAIN: 1152
  MAX_SIZE_TEST: 1152
  FORMAT: "RGB"
  GAUSSIAN_SIGMA: 8
  MASK_FORMAT: "bitmask"
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (384, 1152)
DATALOADER:
  NUM_WORKERS: 4
